// require("./src/1-DarkMode/main")
// require("./src/4-键盘快捷键/1-本地快捷键/main")
// require("./src/4-键盘快捷键/2-全局快捷键/main")
// require("./src/4-键盘快捷键/3-在浏览窗口内的快捷方式/1-使用webapi/main")
// require("./src/4-键盘快捷键/3-在浏览窗口内的快捷方式/2-拦截主进程中的事件/main")
// require("./src/8-原生文件拖与放/main")
// require("./src/12-在线和离线事件探测/main")
// require("./src/13-进度条/main")
// require("./src/17-托盘tray/main")
require("./src/19-任务栏自定义/1-弹出列表/main")